FROM eclipse-temurin:17.0.14_7-jdk AS build-stage

WORKDIR /app

COPY gradle gradle
COPY build.gradle.kts gradlew ./

RUN chmod +x gradlew && \
    ./gradlew dependencies --no-daemon

COPY . .

RUN ./gradlew clean build -x test --no-daemon

FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

COPY --from=build-stage /app/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
